### ISSUE TITLE
preferredLayoutAttributesFittingAttributes issue

### ISSUE THREAD

**Issue by mythodeia** [ShinobiControls/iOS8-day-by-day#10]
Hello
i am using the preferredLayoutAttributesFittingAttributes to auto size the cell in my collection view.
However the top contentinsets of the 1st cell is not respected and it starts from the top without any 
margin. However when the datasource consists of only 1 cell then the top content inset is respected.
Do you know of any solutions/workarounds for this matter?

thanks

**Comment by sammyd** [comment]
I'm sorry - I haven't come across this. Have you got a sample project that demos this problem? I'm happy to take a look and try to help you to determine whether or not it is a UIKit bug.

You could check the dev forums to see whether anybody else has reported similar issues.

If you do have a simple sample project then feel free to ping me the link to the repo on sdavies at shinobicontrols dot com

sam
