### ISSUE TITLE
Should learn this 'iOS8-day-by-day' before 'iOS9-day-by-day'?

### ISSUE THREAD

**Issue by yinzSE** [shinobicontrols/iOS8-day-by-day#15]
I've learned some simple `swift` syntax.

I installed with OS X 10.11 and  Xcode 7.0.

I want to learn to write programs using swift2.0.

This  **iOS8-day-by-day** is suitable for me?

**Comment by sammyd** [comment]
This project highlights all the features that are new to iOS 8, and is current with Swift 1.2 syntax. I don't think it would be appropriate as a beginner resource - maybe once you've got up to speed with building iOS apps then you could pop back here and learn about some of the newer features to the OS.

I'd suggest that you do some searching for "learn to code iOS with swift" and see what beginner level content is available.
