### ISSUE TITLE
cloud kit project need an update for Xcode 6.3 

### ISSUE THREAD

**Issue by abdulazizalmass** [shinobicontrols/iOS8-day-by-day#16]
1
/iOS8-day-by-day-master/33-cloudkit/CloudNotes/CloudNotes/NoteManager.swift:74:27: Cannot invoke initializer for type 'CKModifyRecordsOperation' with an argument list of type '(recordsToSave: [CloudKitNote], recordIDsToDelete: NilLiteralConvertible)'

2
/iOS8-day-by-day-master/33-cloudkit/CloudNotes/CloudNotes/Note.swift:42:7: Type 'CloudKitNote' does not conform to protocol 'Note'

please help

**Comment by abdulazizalmass** [comment]
anybody there ?

**Comment by Kai2k** [comment]
Hi abdulazizalmass.
Just a quick note to say that your message has been received by shinobicontrols (who I work for) and someone will take a look at it in due course. 
Thanks, Kai.

**Comment by MrAPolk** [comment]
This has now been updated to the latest version of XCode (7) & includes support for Swift 2.0.
